(function () {
  "use strict";
  const root = document.getElementById("content");
  const page = document.body.dataset.page;
  const jsonHeaders = { Accept: "application/json" };
  const e = (value) => String(value ?? "").replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[char]));
  const num = (value) => new Intl.NumberFormat("en-US").format(Number(value || 0));
  const money = (value) => "$" + Number(value || 0).toFixed(Number(value || 0) < 0.01 ? 5 : 2);
  const when = (value) => value ? new Date(Number(value) || value).toLocaleString([], { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }) : "—";
  const badge = (value) => `<span class="badge ${e(value)}">${e(value || "unknown")}</span>`;
  const empty = (title, text) => `<div class="empty"><b>${e(title)}</b><div>${e(text)}</div></div>`;
  const head = (eyebrow, title, copy) => `<header class="page-head"><div><p class="eyebrow">${e(eyebrow)}</p><h1>${e(title)}</h1></div><p>${e(copy)}</p></header>`;
  const panel = (title, copy, body, count) => `<section class="panel"><div class="panel-head"><div><h2>${e(title)}</h2>${copy ? `<p>${e(copy)}</p>` : ""}</div>${count == null ? "" : `<span class="count">${num(count)} records</span>`}</div>${body}</section>`;
  const table = (heads, rows) => rows.length ? `<div class="table-wrap"><table><thead><tr>${heads.map((h) => `<th>${e(h)}</th>`).join("")}</tr></thead><tbody>${rows.join("")}</tbody></table></div>` : empty("No records yet", "New records will appear here automatically.");
  async function get(url) { const response = await fetch(url, { headers: jsonHeaders }); if (!response.ok) throw new Error(`${response.status} ${response.statusText}`); return response.json(); }
  async function mutate(url, method, body) { const response = await fetch(url, { method, headers: { ...jsonHeaders, "content-type": "application/json" }, body: JSON.stringify(body || {}) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || `${response.status} ${response.statusText}`); return data; }
  function showError(error) { root.innerHTML = `<div class="error"><b>Could not load this screen.</b><div>${e(error.message || error)}</div><button class="button secondary" id="retry">Try again</button></div>`; document.getElementById("retry").addEventListener("click", () => location.reload()); }
  function clock() { document.getElementById("clock").textContent = `operations / ${new Date().toLocaleString([], { hour: "2-digit", minute: "2-digit", second: "2-digit" })}`; }
  clock(); setInterval(clock, 1000);

  async function overview() {
    const [data, credentials, reviews] = await Promise.all([get("/admin/overview"), get("/admin/credentials"), get("/admin/access-requests")]);
    const funnelOrder = ["demo_started", "demo_completed", "key_created", "first_request", "first_decision", "first_callback", "first_production_action"];
    const max = Math.max(1, ...funnelOrder.map((key) => data.activation_funnel[key] || 0));
    const funnel = `<div class="funnel">${funnelOrder.map((key) => `<div class="funnel-row"><span>${e(key.replaceAll("_", " "))}</span><div class="track"><i style="width:${Math.round((data.activation_funnel[key] || 0) / max * 100)}%"></i></div><b>${num(data.activation_funnel[key])}</b></div>`).join("")}</div>`;
    const eventRows = (data.events_last_24h || []).slice(0, 10).map((item) => `<div class="event"><i class="${/failed|denied|suspend|revoke/i.test(item.outcome || "") ? "bad" : ""}"></i><div><b>${e(item.event_type)}</b><small>${e(item.outcome || "recorded")}</small></div><time>${num(item.c)}</time></div>`).join("");
    const attention = credentials.filter((item) => item.status !== "active" || item.risk_level !== "low").slice(0, 8);
    const attentionRows = attention.map((item) => `<tr><td><code>${e(item.key_prefix)}…</code><small>${e(item.label || item.id)}</small></td><td>${badge(item.status)}</td><td>${badge(item.grant?.risk_state || item.risk_level)}</td><td>${when(item.last_used_at)}</td></tr>`);
    root.innerHTML = head("Control room", "Know what needs action.", "Traffic, activation, reliability, cost, and security are collected here. The incident record remains the source of truth.") +
      `<section class="metrics"><div class="metric"><span>Protected actions</span><strong>${num(Object.values(data.approvals || {}).reduce((a, b) => a + b, 0))}</strong></div><div class="metric"><span>Pending decisions</span><strong>${num(data.approvals?.pending)}</strong></div><div class="metric"><span>Callbacks retrying</span><strong>${num(data.callbacks_retrying)}</strong></div><div class="metric ${data.incidents_open ? "alert" : ""}"><span>Open incidents</span><strong>${num(data.incidents_open)}</strong></div><div class="metric"><span>Estimated today</span><strong>${money(data.estimated_cost_today_usd)}</strong></div></section>` +
      `<div class="grid">${panel("Activation funnel", "Each first_* milestone counts once per account.", funnel)}${panel("Last 24 hours", "Operational events without request content.", `<div class="stack">${eventRows || empty("Quiet day", "No operational events in the last 24 hours.")}</div>`)}</div>` +
      `<div class="toolbar"><h2>Needs attention</h2><span>${reviews.filter((r) => r.status === "PENDING").length} access reviews pending</span></div>${panel("Credentials outside normal", "Restricted, throttled, suspended, revoked, or elevated-risk keys.", table(["Key", "Status", "Risk state", "Last used"], attentionRows), attention.length)}`;
  }

  async function keyRequests() {
    const [requests, reviews] = await Promise.all([get("/admin/key-requests"), get("/admin/access-requests")]);
    const pending = reviews.filter((item) => item.status === "PENDING");
    const requestRows = requests.map((item) => `<tr><td>${when(item.at)}</td><td>${e(item.email)}</td><td>${e(item.tool || "—")}</td><td>${e(item.note || "—")}</td></tr>`);
    const reviewBody = pending.length ? pending.map((item) => `<details class="detail" data-review="${e(item.id)}"><summary>${e(item.intended_use || "No use case supplied")} · ${e(item.id)}</summary><div class="detail-grid"><div class="score"><span>Identity confidence</span><b>${num(item.identity_confidence)}/5</b></div><div class="score"><span>Intended use</span><b>${num(item.intended_use_score)}/5</b></div><div class="score"><span>Blast radius</span><b>${num(item.blast_radius_score)}/5</b></div><div class="score"><span>Behavioral history</span><b>${num(item.behavioral_history_score)}/5</b></div></div><div class="mono">Requested limits: ${e(item.requested_limits)}</div><form class="review-form"><select name="outcome"><option>APPROVE</option><option selected>APPROVE_WITH_LIMITS</option><option>REQUEST_INFO</option><option>DENY</option></select><input name="reason" required placeholder="Why this decision?" maxlength="2000"><button class="button">Record decision</button></form></details>`).join("") : empty("No reviews waiting", "New high-volume access requests will appear here.");
    root.innerHTML = head("Access desk", "Verify first. Review the blast radius.", "Email verification unlocks a small real key. Larger capabilities and limits stay here until an operator records a reasoned decision.") + `<div class="split">${panel("Elevated access reviews", "The four scores guide review; they do not replace judgment.", reviewBody, pending.length)}${panel("Recent key requests", "Landing requests and verification attempts.", table(["Time", "Email", "Tool", "Use case"], requestRows), requests.length)}</div>`;
    document.querySelectorAll(".review-form").forEach((form) => form.addEventListener("submit", async (event) => { event.preventDefault(); const detail = form.closest("[data-review]"); const button = form.querySelector("button"); button.disabled = true; try { await mutate(`/admin/access-requests/${detail.dataset.review}`, "PATCH", { outcome: form.outcome.value, reason: form.reason.value }); detail.remove(); } catch (error) { button.disabled = false; form.reason.setCustomValidity(error.message); form.reason.reportValidity(); } }));
  }

  async function accounts() {
    const [accounts, credentials] = await Promise.all([get("/admin/accounts"), get("/admin/credentials")]);
    const rows = credentials.map((item) => { const limits = item.grant?.limits || {}; return `<tr><td><code>${e(item.key_prefix)}…</code><small>${e(item.label || item.id)}</small></td><td>${badge(item.status)} <small>${badge(item.grant?.risk_state || item.risk_level)}</small></td><td><form class="key-editor" data-key="${e(item.id)}"><select name="status"><option${item.status === "active" ? " selected" : ""}>active</option><option${item.status === "throttled" ? " selected" : ""}>throttled</option><option${item.status === "suspended" ? " selected" : ""}>suspended</option><option${item.status === "revoked" ? " selected" : ""}>revoked</option></select><input class="caps" name="capabilities" value="${e((item.grant?.capabilities || []).join(", "))}" aria-label="Capabilities"><input type="number" min="1" name="rpm" value="${e(limits.rpm || 10)}" aria-label="RPM"><input type="number" min="1" name="pending" value="${e(limits.pending || 10)}" aria-label="Pending limit"><input type="number" min="1" name="approvals_month" value="${e(limits.approvals_month || 50)}" aria-label="Monthly approvals"><input type="number" min="0" name="emails_month" value="${e(limits.emails_month || 30)}" aria-label="Monthly emails"><span class="key-actions"><button class="button" type="submit">Save</button><button class="button secondary rotate" type="button">Rotate</button></span></form></td><td>${when(item.last_used_at)}</td></tr>`; });
    const accountRows = accounts.map((item) => `<tr><td>${e(item.email)}</td><td>${badge(item.email_verified_at ? "verified" : "unverified")}</td><td>${when(item.first_request_at)}</td><td>${when(item.first_production_action_at)}</td><td>${when(item.created_at)}</td></tr>`);
    root.innerHTML = head("Accounts and keys", "Limit the credential, keep the history.", "Edit limits and state without deleting audit history. Rotate replaces a key; revoke is permanent and must include a reason through the API.") + `<div class="notice" id="secret"></div>${panel("Credentials", "Limit columns: RPM, pending, approvals/month, emails/month.", table(["Key", "State", "Limits and action", "Last used"], rows), credentials.length)}<div class="toolbar"><h2>Verified accounts</h2><span>Activation milestones</span></div>${panel("Accounts", "Email verification and first production success.", table(["Account", "Verification", "First request", "First production action", "Created"], accountRows), accounts.length)}`;
    document.querySelectorAll(".key-editor").forEach((form) => {
      form.addEventListener("submit", async (event) => { event.preventDefault(); const button = form.querySelector("button[type=submit]"); button.disabled = true; try { await mutate(`/admin/credentials/${form.dataset.key}`, "PATCH", { status: form.status.value, risk_level: form.status.value === "active" ? "low" : form.status.value === "throttled" ? "high" : "critical", capabilities: form.capabilities.value.split(",").map((value) => value.trim()).filter(Boolean), limits: { rpm: +form.rpm.value, pending: +form.pending.value, approvals_month: +form.approvals_month.value, emails_month: +form.emails_month.value }, revoke_reason: form.status.value === "revoked" ? "ADMIN_REVOKED" : undefined }); button.textContent = "Saved"; setTimeout(() => { button.textContent = "Save"; button.disabled = false; }, 900); } catch (error) { button.disabled = false; button.textContent = "Failed"; } });
      form.querySelector(".rotate").addEventListener("click", async (event) => { const button = event.currentTarget; if (button.dataset.confirm !== "yes") { button.dataset.confirm = "yes"; button.textContent = "Rotate now"; return; } button.disabled = true; try { const result = await mutate(`/admin/credentials/${form.dataset.key}/rotate`, "POST"); const secret = document.getElementById("secret"); secret.textContent = `Copy the new key now: ${result.key}`; secret.classList.add("show"); form.status.value = "revoked"; button.textContent = "Rotated"; } catch (error) { button.disabled = false; button.textContent = "Try again"; } });
    });
  }

  async function traffic() {
    const usage = await get("/admin/traffic"); const totals = usage.reduce((a, row) => ({ approvals: a.approvals + row.approvals_created, decisions: a.decisions + row.decisions, callbacks: a.callbacks + row.callback_attempts, failures: a.failures + row.callback_failures }), { approvals: 0, decisions: 0, callbacks: 0, failures: 0 });
    const rows = usage.map((item) => `<tr><td>${e(item.day)}</td><td><code>${e(item.credential_id)}</code></td><td>${num(item.approvals_created)}</td><td>${num(item.decisions)}</td><td>${num(item.callback_attempts)}</td><td>${num(item.callback_failures)}</td></tr>`);
    root.innerHTML = head("Traffic", "Watch volume before it becomes cost.", "Daily protected actions and callback work are attributed to credentials. Risk monitoring uses shorter rolling windows in the background.") + `<section class="metrics"><div class="metric"><span>Created</span><strong>${num(totals.approvals)}</strong></div><div class="metric"><span>Decisions</span><strong>${num(totals.decisions)}</strong></div><div class="metric"><span>Callback attempts</span><strong>${num(totals.callbacks)}</strong></div><div class="metric ${totals.failures ? "alert" : ""}"><span>Callback failures</span><strong>${num(totals.failures)}</strong></div></section>${panel("Daily usage", "Most recent records first.", table(["Day", "Credential", "Created", "Decisions", "Callback attempts", "Failures"], rows), usage.length)}`;
  }

  async function reliability() {
    const data = await get("/admin/reliability"); const callbackTotal = data.callbacks.reduce((sum, item) => sum + item.count, 0); const delivered = data.callbacks.find((item) => item.state === "delivered")?.count || 0; const rate = callbackTotal ? delivered / callbackTotal * 100 : 100;
    const bars = `<div class="bars">${data.callbacks.map((item) => `<div class="bar"><span>${e(item.state)}</span><div class="bar-track"><i style="width:${callbackTotal ? item.count / callbackTotal * 100 : 0}%"></i></div><b>${num(item.count)}</b></div>`).join("")}</div>`;
    const rows = data.recent_deliveries.map((item) => `<tr><td>${when(item.at)}</td><td><code>${e(item.approval_id)}</code></td><td>${num(item.attempt)}</td><td>${item.status_code ? num(item.status_code) : "—"}</td><td>${e(item.error || "—")}</td></tr>`);
    root.innerHTML = head("Reliability", "A decision is only useful when it arrives.", "Callback retries preserve the same approval ID. Gone one-time endpoints stop retrying; transient failures remain queued until the retry budget ends.") + `<section class="metrics"><div class="metric"><span>Delivery rate</span><strong>${rate.toFixed(1)}%</strong></div><div class="metric"><span>Delivered</span><strong>${num(delivered)}</strong></div><div class="metric"><span>Total outbox</span><strong>${num(callbackTotal)}</strong></div></section><div class="split">${panel("Callback states", "Current outbox distribution.", bars)}${panel("Delivery attempts", "Latest provider responses.", table(["Time", "Approval", "Attempt", "HTTP", "Error"], rows), rows.length)}</div>`;
  }

  async function incidents() {
    const data = await get("/admin/incidents"); const open = data.incidents.filter((item) => item.status === "OPEN").length; const rows = data.incidents.map((item) => `<tr><td>${when(item.created_at)}</td><td>${badge(item.severity)}</td><td><b>${e(item.title)}</b><small>${e(item.credential_id || "global")}</small></td><td>${badge(item.status)}</td><td><div class="actions">${item.status === "OPEN" ? `<button class="button secondary incident-action" data-id="${e(item.id)}" data-status="ACKNOWLEDGED">Acknowledge</button>` : ""}${item.status !== "RESOLVED" ? `<button class="button incident-action" data-id="${e(item.id)}" data-status="RESOLVED">Resolve</button>` : ""}</div></td></tr>`);
    const signalRows = data.signals.map((item) => `<tr><td>${when(item.at)}</td><td>${e(item.signal_type)}</td><td>${badge(item.severity)}</td><td><code>${e(item.credential_id || "global")}</code></td><td>${num(item.observed_value)} / ${item.baseline_value == null ? "—" : num(item.baseline_value)}</td></tr>`);
    root.innerHTML = head("Incidents", "Contain first. Investigate from one record.", "Only high and critical incidents wake the operator in Slack. This screen keeps the complete state and evidence history.") + `<section class="metrics"><div class="metric ${open ? "alert" : ""}"><span>Open</span><strong>${num(open)}</strong></div><div class="metric"><span>All incidents</span><strong>${num(data.incidents.length)}</strong></div><div class="metric"><span>Recent signals</span><strong>${num(data.signals.length)}</strong></div></section>${panel("Incident queue", "Acknowledge ownership, then resolve after investigation.", table(["Created", "Severity", "Incident", "State", "Action"], rows), data.incidents.length)}<div class="toolbar"><h2>Signal evidence</h2><span>Rolling baseline and rules</span></div>${panel("Recent risk signals", "No request body or raw IP is stored here.", table(["Observed", "Signal", "Severity", "Credential", "Value / baseline"], signalRows), data.signals.length)}`;
    document.querySelectorAll(".incident-action").forEach((button) => button.addEventListener("click", async () => { button.disabled = true; try { await mutate(`/admin/incidents/${button.dataset.id}`, "PATCH", { status: button.dataset.status }); await incidents(); } catch (error) { button.disabled = false; button.textContent = "Failed"; } }));
  }

  async function costs() {
    const data = await get("/admin/costs"); const max = Math.max(0.000001, ...data.by_category.map((item) => item.estimated));
    const bars = `<div class="bars">${data.by_category.map((item) => `<div class="bar"><span>${e(item.category)}</span><div class="bar-track"><i style="width:${item.estimated / max * 100}%"></i></div><b>${money(item.estimated)}</b></div>`).join("")}</div>`;
    const keyRows = data.top_keys.map((item) => `<tr><td><code>${e(item.credential_id || "unattributed")}</code></td><td>${money(item.estimated)}</td></tr>`);
    root.innerHTML = head("Costs", "Estimate now. Reconcile later.", "The live ledger gives an early warning. Provider invoices remain separate actual costs, so estimates never pretend to be settled bills.") + `<section class="metrics"><div class="metric"><span>Estimated today</span><strong>${money(data.today.estimated)}</strong></div><div class="metric"><span>Estimated MTD</span><strong>${money(data.mtd.estimated)}</strong></div><div class="metric"><span>Actual MTD</span><strong>${money(data.mtd.actual)}</strong></div><div class="metric"><span>Projected month</span><strong>${money(data.projected_month_estimated_usd)}</strong></div></section><div class="split">${panel("Cost categories", "Compute, storage, delivery, retries, and providers.", bars || empty("No cost entries", "Costs appear after protected actions."))}${panel("Unit cost", "Current month estimates.", `<div class="stack"><div class="event"><i></i><div><b>Protected action</b><small>request, storage, and delivery</small></div><time>${money(data.unit_costs.per_protected_action)}</time></div><div class="event"><i></i><div><b>Email</b><small>transactional delivery</small></div><time>${money(data.unit_costs.per_email)}</time></div><div class="event"><i></i><div><b>Callback attempt</b><small>external delivery</small></div><time>${money(data.unit_costs.per_callback)}</time></div></div>`)}</div><div class="toolbar"><h2>Largest cost keys</h2><span>Global guardrail ${money(data.guardrails.global_daily_usd)} / day</span></div>${panel("Top credentials", "Estimated month-to-date attribution.", table(["Credential", "Estimated cost"], keyRows), keyRows.length)}`;
  }

  const screens = { "/admin": overview, "/admin/key-requests": keyRequests, "/admin/accounts": accounts, "/admin/traffic": traffic, "/admin/reliability": reliability, "/admin/incidents": incidents, "/admin/costs": costs };
  Promise.resolve(screens[page] ? screens[page]() : overview()).catch(showError);
})();
