(function () {
  "use strict";
  const root = document.getElementById("content");
  const page = document.body.dataset.page;
  const e = (v) => String(v ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
  const num = (v) => new Intl.NumberFormat().format(Number(v || 0));
  const when = (v) => v ? new Date(Number(v) || v).toLocaleString([], { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }) : "Never";
  const badge = (v) => `<span class="badge ${e(v)}">${e(v || "unknown")}</span>`;
  const head = (k, t, c) => `<header class="page-head"><div><p class="eyebrow">${e(k)}</p><h1>${e(t)}</h1></div><p>${e(c)}</p></header>`;
  const empty = (t, c) => `<div class="empty"><b>${e(t)}</b><div>${e(c)}</div></div>`;
  const panel = (t, c, b, n) => `<section class="panel"><div class="panel-head"><div><h2>${e(t)}</h2>${c ? `<p>${e(c)}</p>` : ""}</div>${n == null ? "" : `<span class="count">${num(n)}</span>`}</div>${b}</section>`;
  async function get(url) { const r = await fetch(url, { headers: { Accept: "application/json" } }); if (!r.ok) throw Error(`${r.status} ${r.statusText}`); return r.json(); }
  async function mutate(url, method, body) { const r = await fetch(url, { method, headers: { Accept: "application/json", "content-type": "application/json" }, body: JSON.stringify(body || {}) }); const data = await r.json().catch(() => ({})); if (!r.ok) throw Error(data.error || r.statusText); return data; }
  function chart(rows) {
    const days = [];
    for (let i = 13; i >= 0; i--) { const d = new Date(); d.setUTCDate(d.getUTCDate() - i); days.push(d.toISOString().slice(0, 10)); }
    const map = Object.fromEntries(rows.map((r) => [r.day, Number(r.visitors)]));
    const values = days.map((d) => map[d] || 0), max = Math.max(1, ...values);
    const points = values.map((v, i) => `${12 + i * (676 / (values.length - 1))},${174 - v / max * 142}`).join(" ");
    return `<svg class="chart" viewBox="0 0 700 190" role="img" aria-label="Real visitors over 14 days"><defs><linearGradient id="chartFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#145c45" stop-opacity=".18"/><stop offset="1" stop-color="#145c45" stop-opacity="0"/></linearGradient></defs><polygon class="area" points="12,174 ${points} 688,174"/><polyline class="line" points="${points}"/></svg><div class="chart-labels"><span>${days[0].slice(5)}</span><span>Known bots excluded</span><span>Today</span></div>`;
  }
  async function overview() {
    const [ops, traffic, goals, requests, keys] = await Promise.all([get("/admin/overview"), get("/admin/traffic"), get("/admin/goals"), get("/admin/key-requests"), get("/admin/credentials")]);
    const current = goals.goals.find((x) => x.horizon === "CURRENT") || goals.goals[0];
    const visitors = Number(traffic.totals?.visitors || 0);
    const valid = requests.filter((x) => x.classification === "VALID_REQUEST").length;
    const production = goals.evidence.first_production_actions || 0;
    const tasks = [];
    const unclassified = requests.filter((x) => !x.classification || x.classification === "UNCLASSIFIED").length;
    if (unclassified) tasks.push(["warn", "Review new requests", `${unclassified} need a decision`, "/admin/key-requests"]);
    if (keys.some((x) => x.status !== "active" && !["revoked", "blocked"].includes(x.status))) tasks.push(["bad", "Check limited keys", "One or more keys need attention", "/admin/accounts"]);
    if (ops.callbacks_retrying || ops.incidents_open) tasks.push(["bad", "Check delivery health", `${ops.callbacks_retrying} retrying · ${ops.incidents_open} incidents`, "/admin/accounts"]);
    if (!tasks.length) tasks.push(["", "Help one real user finish", `${valid} valid requests · ${production} real workflows completed`, "/admin/key-requests"]);
    root.innerHTML = head("Today", "Get one real workflow through its first safe decision.", "Only the numbers and actions that move the current goal.") +
      `<section class="metrics"><div class="metric"><span>Real visitors · 7d</span><strong>${num(visitors)}</strong></div><div class="metric"><span>Valid requests</span><strong>${num(valid)}</strong></div><div class="metric"><span>Real workflows completed</span><strong>${num(production)}</strong></div><div class="metric"><span>Verified templates</span><strong>${num(goals.evidence.verified_templates)}</strong></div></section>` +
      `<div class="grid">${panel("Real people visiting", "Daily unique browsers. Bots, previews, monitors and prefetches are excluded.", chart(traffic.daily))}${panel("Do next", "Work from top to bottom.", `<div class="todo">${tasks.map((x) => `<a href="${x[3]}"><i class="dot ${x[0]}"></i><span><b>${e(x[1])}</b><small>${e(x[2])}</small></span><b>→</b></a>`).join("")}</div>`)}</div>` +
      `<div class="toolbar"><h2>Current goal</h2><span>${num(current.current_value)} / ${num(current.target_value)}</span></div><article class="goal-card"><h2>${e(current.title)}</h2><p>${e(current.outcome)}</p><div class="goal-progress"><div class="track"><i style="width:${Math.min(100, current.completion || 0)}%"></i></div></div></article>`;
  }
  function keyCard(key) {
    const limits = key.grant?.limits || {}, dead = ["revoked", "blocked"].includes(key.status);
    return `<article class="key-card"><div class="key-summary"><div><b>${e(key.label || "Unnamed key")}</b><small><code>${e(key.key_prefix)}…</code></small></div>${badge(key.status)}<small>Last used ${when(key.last_used_at)}</small></div><details><summary>Manage key and limits</summary><form class="key-editor" data-key="${e(key.id)}"><label>Status<select name="status"${dead ? " disabled" : ""}><option${key.status === "active" ? " selected" : ""}>active</option><option${key.status === "throttled" ? " selected" : ""}>throttled</option><option${key.status === "suspended" ? " selected" : ""}>suspended</option>${dead ? `<option selected>${e(key.status)}</option>` : ""}</select></label><label>Approvals per month<input name="approvals_month" type="number" min="1" value="${e(limits.approvals_month || 50)}"${dead ? " disabled" : ""}></label><label>Requests per minute<input name="rpm" type="number" min="1" value="${e(limits.rpm || 10)}"${dead ? " disabled" : ""}></label><label>Pending at once<input name="pending" type="number" min="1" value="${e(limits.pending || 10)}"${dead ? " disabled" : ""}></label><label class="caps">Capabilities<input name="capabilities" value="${e((key.grant?.capabilities || []).join(", "))}"${dead ? " disabled" : ""}></label><label>Reason<select name="reason_code"${dead ? " disabled" : ""}><option value="ABUSE_SUSPECTED">Suspected abuse</option><option value="NO_LONGER_NEEDED">No longer needed</option><option value="INTERNAL_TEST_CLEANUP">Internal test cleanup</option></select></label><label class="key-reason">Why?<input name="reason" placeholder="Required to suspend or revoke"${dead ? " disabled" : ""}></label><div class="key-actions"><button class="button"${dead ? " disabled" : ""}>Save</button><button type="button" class="button secondary rotate"${dead ? " disabled" : ""}>Rotate key</button><button type="button" class="button danger revoke"${dead ? " disabled" : ""}>Revoke</button></div></form></details></article>`;
  }
  async function accounts() {
    const [people, keys] = await Promise.all([get("/admin/accounts"), get("/admin/credentials")]);
    root.innerHTML = head("API keys", "See who owns each key. Open details only when you need them.", "The secret is shown once when a key is created or rotated.") + `<div class="notice" id="secret"></div>` + panel("Keys", "Active keys first. Revoked keys remain as audit records.", `<div class="key-list">${keys.map(keyCard).join("") || empty("No API keys", "A verified request will create the first key.")}</div>`, keys.length) + `<div class="toolbar"><h2>People</h2><span>${people.length}</span></div>` + panel("Accounts", "Verification and real use, without extra columns.", `<div class="key-list">${people.map((p) => `<div class="key-summary"><div><b>${e(p.email)}</b><small>${p.first_production_action_at ? "Completed a real workflow" : "No real workflow completed yet"}</small></div>${badge(p.email_verified_at ? "verified" : "unverified")}<small>${when(p.created_at)}</small></div>`).join("")}</div>`);
    document.querySelectorAll(".key-editor").forEach((form) => {
      form.onsubmit = async (event) => { event.preventDefault(); const button = form.querySelector("button"); button.disabled = true; try { await mutate(`/admin/credentials/${form.dataset.key}`, "PATCH", { status: form.status.value, risk_level: form.status.value === "active" ? "low" : "high", capabilities: form.capabilities.value.split(",").map((x) => x.trim()).filter(Boolean), limits: { rpm: +form.rpm.value, pending: +form.pending.value, approvals_month: +form.approvals_month.value }, revoke_reason_code: form.reason_code.value, revoke_reason: form.reason.value }); button.textContent = "Saved"; } catch { button.textContent = "Failed"; } setTimeout(() => { button.disabled = false; button.textContent = "Save"; }, 900); };
      form.querySelector(".rotate").onclick = async (event) => { const button = event.currentTarget; if (button.dataset.confirm !== "yes") { button.dataset.confirm = "yes"; button.textContent = "Rotate now"; return; } const data = await mutate(`/admin/credentials/${form.dataset.key}/rotate`, "POST"); const notice = document.getElementById("secret"); notice.textContent = `Copy this key now: ${data.key}`; notice.classList.add("show"); };
      form.querySelector(".revoke").onclick = async (event) => { if (!form.reason.value.trim()) { form.reason.setCustomValidity("Add a reason first."); form.reason.reportValidity(); return; } const button = event.currentTarget; if (button.dataset.confirm !== "yes") { button.dataset.confirm = "yes"; button.textContent = "Revoke now"; return; } await mutate(`/admin/credentials/${form.dataset.key}`, "PATCH", { status: "revoked", risk_level: "critical", revoke_reason_code: form.reason_code.value, revoke_reason: form.reason.value }); accounts(); };
    });
  }
  async function requests() {
    const rows = await get("/admin/key-requests?include_deleted=0");
    const cards = rows.map((r) => `<article class="key-card" data-id="${e(r.id)}"><div class="key-summary"><div><b>${e(r.email)}</b><small>${e(r.tool || "Platform not given")} · ${when(r.at)}</small></div>${badge(r.classification || "UNCLASSIFIED")}<small>${r.email_verified_at ? "Email verified" : "Not verified"}</small></div><p>${e(r.note || "No use case supplied.")}</p><form class="classification-form"><select name="classification"><option value="UNCLASSIFIED">Needs review</option><option value="VALID_REQUEST"${r.classification === "VALID_REQUEST" ? " selected" : ""}>Real request</option><option value="INTERNAL_TEST"${r.classification === "INTERNAL_TEST" ? " selected" : ""}>Internal test</option><option value="PROMOTIONAL_SPAM"${r.classification === "PROMOTIONAL_SPAM" ? " selected" : ""}>Spam</option></select><input name="reason" value="${e(r.classification_reason || "")}" placeholder="Why? (short note)"><button class="button">Save</button></form></article>`).join("");
    root.innerHTML = head("Requests", "Find the real person with a real approval problem.", "Classify each request, then help the strongest one complete a workflow.") + panel("Inbox", "Real request means a specific workflow problem from a person you can help.", `<div class="key-list">${cards || empty("Inbox is clear", "New requests will appear here.")}</div>`, rows.length);
    document.querySelectorAll(".classification-form").forEach((form) => form.onsubmit = async (event) => { event.preventDefault(); await mutate(`/admin/key-requests/${form.closest("[data-id]").dataset.id}/classification`, "PATCH", { classification: form.classification.value, reason: form.reason.value }); requests(); });
  }
  const screens = { "/admin": overview, "/admin/accounts": accounts, "/admin/key-requests": requests };
  Promise.resolve((screens[page] || overview)()).catch((error) => { root.innerHTML = `<div class="error"><b>Could not load.</b><div>${e(error.message)}</div></div>`; });
})();
