const NAV = [
  ["/admin", "Overview"],
  ["/admin/key-requests", "Key requests"],
  ["/admin/accounts", "Accounts"],
  ["/admin/traffic", "Traffic"],
  ["/admin/reliability", "Reliability"],
  ["/admin/incidents", "Incidents"],
  ["/admin/costs", "Costs"],
];

function renderAdminConsole(activePath, fallbackHtml = "") {
  const nav = NAV.map(([href, label]) => `<a href="${href}"${href === activePath ? ' aria-current="page"' : ""}>${label}</a>`).join("");
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Someone Has To Say Yes operations console"><title>Operations · someonehastosayyes</title>
  <style>
  :root{color-scheme:light;--paper:#f4f5ef;--surface:#fff;--ink:#161914;--muted:#687066;--line:#d9ddd4;--signal:#dce64a;--signal-ink:#343806;--danger:#9a3730;--danger-soft:#f7e9e6;--warn:#83621a;--warn-soft:#f4edcf;--ok:#236847;--ok-soft:#e5f1e9;--shadow:0 16px 40px rgba(36,42,31,.08)}
  *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--paper);color:var(--ink);font:14px/1.45 Geist,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;-webkit-font-smoothing:antialiased}button,input,select,textarea{font:inherit}button,a{transition:background-color .2s,color .2s,border-color .2s,transform .2s}button:active{transform:translateY(1px)}:focus-visible{outline:2px solid var(--ink);outline-offset:3px}.skip{position:fixed;left:1rem;top:-4rem;z-index:3;background:var(--ink);color:#fff;padding:.7rem 1rem}.skip:focus{top:1rem}
  .mast{border-bottom:1px solid var(--line);background:rgba(244,245,239,.94);backdrop-filter:blur(14px);position:sticky;top:0;z-index:2}.mast-inner{max-width:1400px;margin:auto;padding:18px 28px 0}.brandline{display:flex;align-items:center;justify-content:space-between;gap:24px;margin-bottom:18px}.brand{font-weight:650;letter-spacing:-.03em;font-size:18px}.brand i{display:inline-block;width:8px;height:8px;background:var(--signal);border:1px solid #aab42b;margin-left:7px}.clock{color:var(--muted);font:12px ui-monospace,SFMono-Regular,Menlo,monospace;font-variant-numeric:tabular-nums}.nav{display:flex;gap:26px;overflow:auto;scrollbar-width:none}.nav a{position:relative;color:var(--muted);text-decoration:none;padding:0 0 13px;white-space:nowrap;font-weight:500}.nav a:hover{color:var(--ink)}.nav a[aria-current=page]{color:var(--ink)}.nav a[aria-current=page]:after{content:"";position:absolute;left:0;right:0;bottom:-1px;height:3px;background:var(--signal)}
  main{max-width:1400px;margin:auto;padding:46px 28px 88px}.page-head{display:grid;grid-template-columns:minmax(0,1fr) minmax(260px,.45fr);gap:44px;align-items:end;margin-bottom:34px}.eyebrow{color:#747b70;font:11px ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.08em;text-transform:uppercase;margin:0 0 10px}.page-head h1{font-size:clamp(34px,5vw,58px);line-height:.98;letter-spacing:-.06em;margin:0;font-weight:620;text-wrap:balance}.page-head p{color:var(--muted);max-width:52ch;margin:0 0 3px;line-height:1.6;text-wrap:pretty}.toolbar{display:flex;justify-content:space-between;align-items:center;gap:12px;margin:30px 0 13px}.toolbar h2{font-size:17px;letter-spacing:-.02em;margin:0}.toolbar span{color:var(--muted);font-size:12px}
  .briefing{background:var(--surface);box-shadow:var(--shadow);border-top:4px solid var(--signal);margin-bottom:30px}.briefing.ACTION{border-top-color:var(--danger)}.briefing.WATCH{border-top-color:#b68a27}.briefing-head{display:grid;grid-template-columns:minmax(0,1fr) 170px;gap:34px;padding:28px 30px 27px;border-bottom:1px solid var(--line);align-items:end}.briefing-head h2{font-size:clamp(25px,3vw,38px);line-height:1.08;letter-spacing:-.045em;margin:0;max-width:24ch;text-wrap:balance}.briefing-head>div>p:last-child{color:var(--muted);margin:12px 0 0}.briefing-stamp{border-left:1px solid var(--line);padding-left:24px}.briefing-stamp span,.briefing-stamp small{display:block;color:var(--muted);font-size:10px;letter-spacing:.04em}.briefing-stamp b{display:block;font:500 42px/1 ui-monospace,SFMono-Regular,Menlo,monospace;margin:12px 0 8px}.briefing-list{display:grid}.briefing-item{display:grid;grid-template-columns:92px minmax(0,1fr) 150px;gap:22px;align-items:start;padding:20px 30px;color:var(--ink);text-decoration:none;border-bottom:1px solid var(--line);box-shadow:inset 3px 0 0 transparent}.briefing-item:last-child{border-bottom:0}.briefing-item:hover{background:#fafbf6}.briefing-item.critical{box-shadow:inset 3px 0 0 var(--danger)}.briefing-item.warning{box-shadow:inset 3px 0 0 #b68a27}.briefing-item.opportunity{box-shadow:inset 3px 0 0 var(--signal)}.briefing-kind{color:var(--muted);font:10px ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.05em;text-transform:uppercase;padding-top:3px}.briefing-item h3{font-size:16px;letter-spacing:-.02em;margin:0 0 5px}.briefing-item p{color:var(--muted);margin:0;max-width:76ch;line-height:1.55}.briefing-item .recommendation{color:var(--ink);margin-top:9px}.recommendation b{display:inline-block;color:var(--muted);font-size:10px;letter-spacing:.05em;margin-right:9px}.briefing-go{justify-self:end;color:var(--ink);font-weight:600;font-size:12px;padding-top:3px;white-space:nowrap}
  .metrics{display:grid;grid-template-columns:1.1fr repeat(4,1fr);border-block:1px solid var(--line);margin-bottom:38px}.metrics.four{grid-template-columns:repeat(4,1fr)}.metrics.filters{grid-template-columns:repeat(5,1fr)}.metric{padding:18px 18px 21px;border-right:1px solid var(--line);min-width:0}.metric:first-child{padding-left:0}.metric:last-child{border-right:0}.metric span{display:block;color:var(--muted);font-size:12px;margin-bottom:17px}.metric strong{display:block;font:500 clamp(24px,3vw,40px)/1 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:-.05em;font-variant-numeric:tabular-nums}.metric.alert strong{color:var(--danger)}.metric-filter{appearance:none;background:transparent;color:inherit;text-align:left;cursor:pointer;border:0;border-right:1px solid var(--line)}.metric-filter:hover{background:rgba(255,255,255,.58)}.metric-filter[aria-pressed=true]{background:rgba(220,230,74,.13);box-shadow:inset 0 -3px 0 var(--signal)}.metric-filter[aria-pressed=true] span{color:var(--ink)}
  .grid{display:grid;grid-template-columns:minmax(0,1.35fr) minmax(280px,.65fr);gap:14px}.panel{background:var(--surface);box-shadow:var(--shadow);padding:22px;min-width:0}.panel.soft{background:#eceee6;box-shadow:none}.panel h2,.panel h3{margin:0;letter-spacing:-.025em}.panel h2{font-size:20px}.panel h3{font-size:15px}.panel-head{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;margin-bottom:18px}.panel-head p{margin:4px 0 0;color:var(--muted);font-size:13px}.count{font:12px ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--muted)}
  .table-wrap{overflow:auto;margin:0 -22px -22px}table{border-collapse:collapse;width:100%;min-width:700px}th,td{text-align:left;padding:12px 14px;border-top:1px solid #e8eae4;vertical-align:middle;white-space:nowrap}th:first-child,td:first-child{padding-left:22px}th:last-child,td:last-child{padding-right:22px}th{color:var(--muted);font-size:10px;letter-spacing:.07em;text-transform:uppercase;font-weight:600}td{font-size:13px}td small{display:block;color:var(--muted);margin-top:2px}code,.mono{font:12px ui-monospace,SFMono-Regular,Menlo,monospace;font-variant-numeric:tabular-nums}.badge{display:inline-block;padding:3px 7px;border:1px solid var(--line);font:10px ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.04em}.badge.good,.badge.NORMAL,.badge.active,.badge.delivered,.badge.APPROVE{background:var(--ok-soft);border-color:#c0d9c9;color:var(--ok)}.badge.warn,.badge.WATCH,.badge.THROTTLED,.badge.throttled,.badge.restricted,.badge.queued{background:var(--warn-soft);border-color:#dfd19f;color:var(--warn)}.badge.bad,.badge.HIGH,.badge.CRITICAL,.badge.SUSPENDED,.badge.REVOKED,.badge.suspended,.badge.revoked,.badge.failed{background:var(--danger-soft);border-color:#e7c4be;color:var(--danger)}
  .stack{display:grid;gap:9px}.event{display:grid;grid-template-columns:9px minmax(0,1fr) auto;gap:11px;align-items:start;padding:11px 0;border-bottom:1px solid var(--line)}.event:last-child{border-bottom:0}.event i{width:7px;height:7px;background:#949b8e;margin-top:6px}.event i.bad{background:var(--danger)}.event b{display:block;font-size:13px;font-weight:570}.event small{color:var(--muted)}.event time{color:var(--muted);font:10px ui-monospace,SFMono-Regular,Menlo,monospace}.funnel{display:grid;gap:12px}.funnel-row{display:grid;grid-template-columns:128px 1fr 46px;gap:10px;align-items:center}.funnel-row span{color:var(--muted);font-size:12px}.track{height:7px;background:#dfe2da;overflow:hidden}.track i{display:block;height:100%;background:var(--signal)}.funnel-row b{text-align:right;font:12px ui-monospace,SFMono-Regular,Menlo,monospace}
  .empty,.error,.loading{padding:42px 22px;text-align:center;color:var(--muted);border:1px dashed var(--line);background:rgba(255,255,255,.45)}.error{color:var(--danger);border-color:#dfb9b4;background:var(--danger-soft)}.skeleton{height:12px;background:linear-gradient(90deg,#e4e7df 25%,#f2f3ee 50%,#e4e7df 75%);background-size:200% 100%;animation:shimmer 1.2s infinite;margin:10px 0}@keyframes shimmer{to{background-position:-200% 0}}
  .button{border:1px solid var(--ink);background:var(--ink);color:#fff;padding:7px 11px;cursor:pointer;font-weight:570}.button:hover{background:#30352d}.button.secondary{background:#fff;color:var(--ink);border-color:var(--line)}.button.secondary:hover{border-color:var(--ink)}.button.danger{background:#fff;color:var(--danger);border-color:#d8aaa4}.button.danger:hover{background:var(--danger-soft);border-color:var(--danger)}.button.signal{background:var(--signal);color:var(--signal-ink);border-color:#aeb82d}.button:disabled{opacity:.45;cursor:not-allowed}.actions{display:flex;gap:6px;align-items:center}.field,select,textarea,input{border:1px solid var(--line);background:#fff;color:var(--ink);padding:8px 9px;min-width:0}textarea{resize:vertical}.inline-form{display:grid;grid-template-columns:1fr 1fr auto;gap:8px}.notice{padding:12px 14px;background:var(--signal);color:var(--signal-ink);margin-bottom:16px;font-weight:550;display:none;word-break:break-all}.notice.show{display:block}.detail{padding:14px 0;border-top:1px solid var(--line)}.detail summary{cursor:pointer;font-weight:570}.detail-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:12px 0}.score{background:#eceee6;padding:10px}.score span{display:block;color:var(--muted);font-size:10px}.score b{font:20px ui-monospace,SFMono-Regular,Menlo,monospace}.review-form{display:grid;grid-template-columns:180px minmax(200px,1fr) auto;gap:8px;margin-top:12px}.bars{display:grid;gap:10px}.bar{display:grid;grid-template-columns:130px minmax(90px,1fr) 80px;gap:10px;align-items:center}.bar span{font-size:12px;color:var(--muted)}.bar-track{height:9px;background:#e1e4dc}.bar-track i{display:block;height:100%;background:#6c7366}.bar b{text-align:right;font:11px ui-monospace,SFMono-Regular,Menlo,monospace}.split{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.key-editor{display:grid;grid-template-columns:130px minmax(220px,1fr) repeat(4,88px) 170px minmax(190px,1fr) auto;gap:6px;align-items:center}.key-editor input{width:88px}.key-editor input.caps,.key-editor input.key-reason{width:100%}.key-editor select{width:130px}.key-editor select.key-reason-code{width:170px}.key-actions{display:flex;gap:5px;flex-wrap:wrap}
  .triage-list{display:grid}.triage-item{padding:18px 0;border-top:1px solid var(--line)}.triage-item:first-child{border-top:0}.triage-item.archived{opacity:.78}.triage-item header{display:flex;align-items:flex-start;justify-content:space-between;gap:16px}.triage-item header b,.triage-item header small{display:block}.triage-item header b{font-size:15px;overflow-wrap:anywhere}.triage-item header small,.classification-meta{color:var(--muted);font-size:11px;margin-top:3px}.badge-pair{display:flex;gap:5px;flex-wrap:wrap;justify-content:flex-end}.triage-signals{display:flex;flex-wrap:wrap;gap:5px;margin:11px 0}.triage-signals span{background:#eceee6;padding:4px 7px;color:var(--muted);font-size:10px}.triage-note{max-width:78ch;margin:11px 0 14px;white-space:pre-wrap;color:#3f443c;font-size:13px;max-height:112px;overflow:auto}.classification-form{display:grid;grid-template-columns:210px minmax(220px,1fr) auto;gap:7px}.classification-meta{margin-bottom:0}.management-form{display:grid;grid-template-columns:190px minmax(240px,1fr) auto;gap:7px;margin-top:14px;padding-top:14px;border-top:1px solid var(--line)}.management-actions{display:flex;gap:6px}.management-warning{margin:7px 0 0;color:var(--muted);font-size:11px}.management-record{display:grid;gap:3px;margin-top:14px;padding:12px;background:var(--danger-soft);color:var(--danger);font-size:11px}.badge.VALID_REQUEST,.badge.ACTIVE{background:var(--ok-soft);border-color:#bdd7c5;color:var(--ok)}.badge.INTERNAL_TEST{background:#eceee6;border-color:#d7dbd1;color:#596057}.badge.PROMOTIONAL_SPAM,.badge.DELETED{background:var(--danger-soft);border-color:#e7c4be;color:var(--danger)}.badge.UNCLASSIFIED,.badge.SUSPENDED{background:var(--warn-soft);border-color:#dfd19f;color:var(--warn)}
  @media(max-width:950px){.page-head,.grid,.split{grid-template-columns:1fr}.briefing-head{grid-template-columns:1fr}.briefing-stamp{border-left:0;border-top:1px solid var(--line);padding:18px 0 0;display:grid;grid-template-columns:1fr auto;align-items:end}.briefing-stamp b{grid-column:2;grid-row:1/3;margin:0}.briefing-item{grid-template-columns:78px minmax(0,1fr)}.briefing-go{grid-column:2;justify-self:start}.metrics{grid-template-columns:repeat(2,1fr)}.metrics.filters{grid-template-columns:repeat(5,minmax(140px,1fr));overflow-x:auto;scrollbar-width:thin}.metric:first-child{padding-left:18px}.metric:nth-child(2n){border-right:0}.metrics.filters .metric{border-right:1px solid var(--line);border-bottom:0}.metrics.filters .metric:last-child{border-right:0}.detail-grid{grid-template-columns:repeat(2,1fr)}.key-editor{grid-template-columns:1fr 1fr}.key-editor select,.key-editor input{width:100%}.key-actions{grid-column:1/-1}.review-form,.inline-form,.classification-form,.management-form{grid-template-columns:1fr}}
  @media(max-width:620px){.mast-inner,main{padding-left:18px;padding-right:18px}.brandline{align-items:flex-start}.clock{display:none}.nav{gap:20px}.page-head{gap:18px;margin-bottom:25px}.briefing-head{padding:22px 20px}.briefing-item{grid-template-columns:1fr;gap:8px;padding:18px 20px}.briefing-go{grid-column:1}.metrics{grid-template-columns:1fr}.metric{border-right:0;border-bottom:1px solid var(--line);padding-left:0}.panel{padding:18px}.table-wrap{margin-left:-18px;margin-right:-18px}.funnel-row{grid-template-columns:105px 1fr 35px}.bar{grid-template-columns:90px 1fr 62px}}
  @media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;animation:none!important;transition:none!important}}
  </style></head><body data-page="${activePath}"><a class="skip" href="#content">Skip to content</a><header class="mast"><div class="mast-inner"><div class="brandline"><div class="brand">someonehastosayyes<i></i></div><div class="clock" id="clock">Operations / loading</div></div><nav class="nav" aria-label="Operations">${nav}</nav></div></header><main id="content"><div class="loading"><div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div></div><noscript>${fallbackHtml}</noscript></main><script src="/admin/app.js" defer></script></body></html>`;
}

module.exports = { renderAdminConsole, screenPaths: NAV.map(([path]) => path) };
