(function () {
  "use strict";
  const root = document.getElementById("content");
  const page = document.body.dataset.page;
  let showArchivedRequests = false;
  let requestClassificationFilter = "ALL";
  const jsonHeaders = { Accept: "application/json" };
  const e = (value) => String(value ?? "").replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[char]));
  const num = (value) => new Intl.NumberFormat("en-US").format(Number(value || 0));
  const money = (value) => "$" + Number(value || 0).toFixed(Number(value || 0) < 0.01 ? 5 : 2);
  const when = (value) => value ? new Date(Number(value) || value).toLocaleString([], { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }) : "—";
  const badge = (value) => `<span class="badge ${e(value)}">${e(value || "unknown")}</span>`;
  const empty = (title, text) => `<div class="empty"><b>${e(title)}</b><div>${e(text)}</div></div>`;
  const head = (eyebrow, title, copy) => `<header class="page-head"><div><p class="eyebrow">${e(eyebrow)}</p><h1>${e(title)}</h1></div><p>${e(copy)}</p></header>`;
  const panel = (title, copy, body, count) => `<section class="panel"><div class="panel-head"><div><h2>${e(title)}</h2>${copy ? `<p>${e(copy)}</p>` : ""}</div>${count == null ? "" : `<span class="count">${num(count)} records</span>`}</div>${body}</section>`;
  const table = (heads, rows) => rows.length ? `<div class="table-wrap"><table><thead><tr>${heads.map((h) => `<th>${e(h)}</th>`).join("")}</tr></thead><tbody>${rows.join("")}</tbody></table></div>` : empty("No records yet", "New records will appear here automatically.");
  async function get(url) { const response = await fetch(url, { headers: jsonHeaders }); if (!response.ok) throw new Error(`${response.status} ${response.statusText}`); return response.json(); }
  async function mutate(url, method, body) { const response = await fetch(url, { method, headers: { ...jsonHeaders, "content-type": "application/json" }, body: JSON.stringify(body || {}) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || `${response.status} ${response.statusText}`); return data; }
  function showError(error) { root.innerHTML = `<div class="error"><b>Could not load this screen.</b><div>${e(error.message || error)}</div><button class="button secondary" id="retry">Try again</button></div>`; document.getElementById("retry").addEventListener("click", () => location.reload()); }
  function clock() { document.getElementById("clock").textContent = `operations / ${new Date().toLocaleString([], { hour: "2-digit", minute: "2-digit", second: "2-digit" })}`; }
  clock(); setInterval(clock, 1000);

  async function overview() {
    const [data, credentials, reviews] = await Promise.all([get("/admin/overview"), get("/admin/credentials"), get("/admin/access-requests")]);
    const funnelOrder = ["demo_started", "demo_completed", "key_created", "first_request", "first_decision", "first_callback", "first_production_action"];
    const funnelLabels = { demo_started: "데모 시작", demo_completed: "데모 완료", key_created: "API Key 발급", first_request: "첫 요청", first_decision: "첫 결정", first_callback: "첫 콜백", first_production_action: "첫 실제 사용 완료" };
    const max = Math.max(1, ...funnelOrder.map((key) => data.activation_funnel[key] || 0));
    const funnel = `<div class="funnel">${funnelOrder.map((key) => `<div class="funnel-row"><span>${e(funnelLabels[key])}</span><div class="track"><i style="width:${Math.round((data.activation_funnel[key] || 0) / max * 100)}%"></i></div><b>${num(data.activation_funnel[key])}</b></div>`).join("")}</div>`;
    const eventRows = (data.events_last_24h || []).slice(0, 10).map((item) => `<div class="event"><i class="${/failed|denied|suspend|revoke/i.test(item.outcome || "") ? "bad" : ""}"></i><div><b>${e(item.event_type)}</b><small>${e(item.outcome || "recorded")}</small></div><time>${num(item.c)}</time></div>`).join("");
    const attention = credentials.filter((item) => !["revoked", "blocked"].includes(item.status) && (item.status !== "active" || item.risk_level !== "low")).slice(0, 8);
    const attentionRows = attention.map((item) => `<tr><td><code>${e(item.key_prefix)}…</code><small>${e(item.label || item.id)}</small></td><td>${badge(item.status)}</td><td>${badge(item.grant?.risk_state || item.risk_level)}</td><td>${when(item.last_used_at)}</td></tr>`);
    const briefing = data.briefing || { status: "CLEAR", headline: "운영 보고를 만들 수 없습니다.", action_count: 0, opportunity_count: 0, items: [] };
    const statusLabels = { ACTION: "즉시 조치", WATCH: "확인 권장", OPPORTUNITY: "성장 기회", CLEAR: "정상" };
    const levelLabels = { critical: "즉시 확인", warning: "확인 권장", opportunity: "성장 기회", good: "정상", info: "참고" };
    const briefingItems = briefing.items.map((item) => `<a class="briefing-item ${e(item.level)}" href="${e(item.href)}"><span class="briefing-kind">${e(levelLabels[item.level] || "보고")}</span><div><h3>${e(item.title)}</h3><p>${e(item.detail)}</p><p class="recommendation"><b>추천</b>${e(item.recommendation)}</p></div><span class="briefing-go">${e(item.action_label)} →</span></a>`).join("");
    const briefingCount = briefing.action_count || briefing.opportunity_count;
    const briefingCountLabel = briefing.action_count ? "확인할 운영 항목" : "오늘의 성장 항목";
    const briefingHtml = `<section class="briefing ${e(briefing.status)}"><header class="briefing-head"><div><p class="eyebrow">오늘의 운영 보고 · ${when(data.generated_at)}</p><h2>${e(briefing.headline)}</h2><p>Admin이 실제 기록을 먼저 읽고 중요한 순서로 정리했습니다.</p></div><div class="briefing-stamp"><span>${e(statusLabels[briefing.status] || "보고")}</span><b>${num(briefingCount)}</b><small>${briefingCountLabel}</small></div></header><div class="briefing-list">${briefingItems}</div></section>`;
    root.innerHTML = head("운영 브리핑", "오늘 확인할 내용을 먼저 정리했습니다.", "Overview만 읽어도 현재 상태와 다음 행동을 알 수 있습니다. 특이점이 있을 때만 연결된 상세 화면으로 이동하세요.") + briefingHtml +
      `<section class="metrics"><div class="metric"><span>보호된 작업</span><strong>${num(Object.values(data.approvals || {}).reduce((a, b) => a + b, 0))}</strong></div><div class="metric"><span>결정 대기</span><strong>${num(data.approvals?.pending)}</strong></div><div class="metric"><span>콜백 재시도</span><strong>${num(data.callbacks_retrying)}</strong></div><div class="metric ${data.incidents_open ? "alert" : ""}"><span>미해결 사고</span><strong>${num(data.incidents_open)}</strong></div><div class="metric"><span>오늘 예상 비용</span><strong>${money(data.estimated_cost_today_usd)}</strong></div></section>` +
      `<div class="grid">${panel("사용자 활성화 흐름", "각 단계는 계정당 최초 1회만 계산합니다.", funnel)}${panel("최근 24시간 자동 기록", "보고의 근거가 된 운영 이벤트입니다.", `<div class="stack">${eventRows || empty("조용한 하루입니다", "최근 24시간 운영 이벤트가 없습니다.")}</div>`)}</div>` +
      `<div class="toolbar"><h2>추가 확인이 필요한 API Key</h2><span>${reviews.filter((r) => r.status === "PENDING").length}건의 사용량 확대 검토 대기</span></div>${panel("현재 조치 대상", "폐기 완료된 키는 제외하고 제한·속도 저하·일시 정지된 키만 표시합니다.", table(["Key", "상태", "위험 상태", "마지막 사용"], attentionRows), attention.length)}`;
  }

  async function keyRequests() {
    const [allRequests, reviews] = await Promise.all([get("/admin/key-requests?include_deleted=1"), get("/admin/access-requests")]);
    const pending = reviews.filter((item) => item.status === "PENDING");
    const archivedCount = allRequests.filter((item) => item.management_state === "DELETED").length;
    const activeRequests = allRequests.filter((item) => item.management_state !== "DELETED");
    const requestPool = showArchivedRequests ? allRequests : activeRequests;
    const requests = requestClassificationFilter === "ALL" ? requestPool : requestPool.filter((item) => (item.classification || "UNCLASSIFIED") === requestClassificationFilter);
    const counts = activeRequests.reduce((result, item) => { const key = item.classification || "UNCLASSIFIED"; result[key] = (result[key] || 0) + 1; return result; }, {});
    const requestBody = requests.length ? `<div class="triage-list">${requests.map((item) => {
      const classification = item.classification || "UNCLASSIFIED";
      const credentials = item.credentials || [];
      const active = credentials.filter((credential) => credential.status === "active").length;
      const usage = credentials.reduce((sum, credential) => ({ approvals: sum.approvals + Number(credential.approvals_created || 0), decisions: sum.decisions + Number(credential.decisions || 0), callbacks: sum.callbacks + Number(credential.callback_attempts || 0) }), { approvals: 0, decisions: 0, callbacks: 0 });
      const isDeleted = item.management_state === "DELETED";
      const management = isDeleted
        ? `<div class="management-record"><b>Archived; linked keys are permanently revoked.</b><span>${e(item.management_reason_code || "ADMIN_DELETE")} · ${e(item.management_reason || "No reason recorded")}</span><span>Usage history remains available above.</span></div>`
        : `<form class="management-form"><select name="reason_code" aria-label="Management reason for ${e(item.email)}"><option value="ABUSE_SUSPECTED">Suspected abuse</option><option value="ABUSE_CONFIRMED">Confirmed abuse</option><option value="NO_LONGER_NEEDED">No longer needed</option><option value="ISSUED_BY_MISTAKE">Issued by mistake</option><option value="INTERNAL_TEST_CLEANUP">Internal test cleanup</option><option value="INVESTIGATION_CLEARED">Investigation cleared</option></select><input name="management_reason" required maxlength="2000" value="${e(item.management_reason || "")}" placeholder="Why are you changing this request and its key?"><span class="management-actions">${item.management_state === "SUSPENDED" ? `<button class="button secondary management-action" type="button" data-action="RESTORE">Restore</button>` : `<button class="button secondary management-action" type="button" data-action="SUSPEND">Suspend</button>`}<button class="button danger management-action" type="button" data-action="DELETE">${credentials.length ? "Delete request + key" : "Delete request"}</button></span></form><p class="management-warning">Suspend is reversible. Delete permanently revokes every linked key, but keeps usage and audit history.</p>`;
      return `<article class="triage-item ${isDeleted ? "archived" : ""}" data-key-request="${e(item.id)}"><header><div><b>${e(item.email)}</b><small>${when(item.at)} · ${e(item.tool || "tool unknown")}</small></div><span class="badge-pair">${badge(classification)}${badge(item.management_state || "ACTIVE")}</span></header><div class="triage-signals"><span>${item.email_verified_at ? "Email verified" : "Email unverified"}</span><span>${credentials.length ? `${num(credentials.length)} key record${credentials.length === 1 ? "" : "s"} · ${num(active)} active` : "No key issued"}</span><span>${num(usage.approvals)} protected actions · ${num(usage.decisions)} decisions · ${num(usage.callbacks)} callbacks</span></div><p class="triage-note">${e(item.note || "No use case supplied.")}</p>${isDeleted ? `<p class="classification-meta">${e(item.classification_reason || "No classification evidence")}</p>` : `<form class="classification-form"><select name="classification" aria-label="Classification for ${e(item.email)}"><option value="UNCLASSIFIED"${classification === "UNCLASSIFIED" ? " selected" : ""}>Needs review</option><option value="VALID_REQUEST"${classification === "VALID_REQUEST" ? " selected" : ""}>Valid request</option><option value="INTERNAL_TEST"${classification === "INTERNAL_TEST" ? " selected" : ""}>Internal test</option><option value="PROMOTIONAL_SPAM"${classification === "PROMOTIONAL_SPAM" ? " selected" : ""}>Promotional / not a key request</option></select><input name="reason" maxlength="2000" value="${e(item.classification_reason || "")}" placeholder="Evidence for this classification"><button class="button" type="submit">Save classification</button></form><p class="classification-meta">${item.classified_at ? `Classified ${when(item.classified_at)} by ${e(item.classified_by || "admin")}` : "Not classified yet"}</p>`}${management}</article>`;
    }).join("")}</div>` : empty("No requests in this view", requestClassificationFilter === "ALL" ? "New landing requests will appear here automatically." : "Choose another filter or All to see other requests.");
    const reviewBody = pending.length ? pending.map((item) => `<details class="detail" data-review="${e(item.id)}"><summary>${e(item.intended_use || "No use case supplied")} · ${e(item.id)}</summary><div class="detail-grid"><div class="score"><span>Identity confidence</span><b>${num(item.identity_confidence)}/5</b></div><div class="score"><span>Intended use</span><b>${num(item.intended_use_score)}/5</b></div><div class="score"><span>Blast radius</span><b>${num(item.blast_radius_score)}/5</b></div><div class="score"><span>Behavioral history</span><b>${num(item.behavioral_history_score)}/5</b></div></div><div class="mono">Requested limits: ${e(item.requested_limits)}</div><form class="review-form"><select name="outcome"><option>APPROVE</option><option selected>APPROVE_WITH_LIMITS</option><option>REQUEST_INFO</option><option>DENY</option></select><input name="reason" required placeholder="Why this decision?" maxlength="2000"><button class="button">Record decision</button></form></details>`).join("") : empty("No reviews waiting", "New high-volume access requests will appear here.");
    const filterMetric = (value, label, count, alert = false) => `<button class="metric metric-filter ${alert ? "alert" : ""}" type="button" data-filter="${value}" aria-pressed="${requestClassificationFilter === value}"><span>${label}</span><strong>${num(count)}</strong></button>`;
    root.innerHTML = head("Access desk", "Control the request and its key together.", "Email verification, linked credentials, and usage stay visible. Suspected abuse can be paused; confirmed abuse can be permanently revoked without losing evidence.") + `<section class="metrics filters" aria-label="Filter key requests">${filterMetric("ALL", "All", activeRequests.length)}${filterMetric("UNCLASSIFIED", "Needs review", counts.UNCLASSIFIED, Boolean(counts.UNCLASSIFIED))}${filterMetric("VALID_REQUEST", "Valid requests", counts.VALID_REQUEST)}${filterMetric("INTERNAL_TEST", "Internal tests", counts.INTERNAL_TEST)}${filterMetric("PROMOTIONAL_SPAM", "Promotional", counts.PROMOTIONAL_SPAM)}</section><div class="toolbar"><h2>Request and key control</h2><button class="button secondary" id="archive-toggle">${showArchivedRequests ? "Hide archived" : `Show archived (${num(archivedCount)})`}</button></div>${panel("Request records", "Deleting a request revokes its linked key in the same operation. Records and usage are archived, never hard-deleted.", requestBody, requests.length)}<div class="toolbar"><h2>Elevated access</h2><span>${pending.length} reviews pending</span></div>${panel("High-volume access reviews", "The four scores guide review; they do not replace judgment.", reviewBody, pending.length)}`;
    document.querySelectorAll(".metric-filter").forEach((button) => button.addEventListener("click", async () => { requestClassificationFilter = button.dataset.filter; await keyRequests(); }));
    document.getElementById("archive-toggle").addEventListener("click", async () => { showArchivedRequests = !showArchivedRequests; await keyRequests(); });
    document.querySelectorAll(".classification-form").forEach((form) => form.addEventListener("submit", async (event) => { event.preventDefault(); const item = form.closest("[data-key-request]"); const button = form.querySelector("button"); button.disabled = true; form.reason.setCustomValidity(""); try { await mutate(`/admin/key-requests/${item.dataset.keyRequest}/classification`, "PATCH", { classification: form.classification.value, reason: form.reason.value }); await keyRequests(); } catch (error) { button.disabled = false; form.reason.setCustomValidity(error.message); form.reason.reportValidity(); } }));
    document.querySelectorAll(".management-action").forEach((button) => button.addEventListener("click", async () => { const form = button.closest(".management-form"); const item = button.closest("[data-key-request]"); const action = button.dataset.action; form.management_reason.setCustomValidity(""); if (!form.management_reason.value.trim()) { form.management_reason.setCustomValidity("Record the reason before changing this request or key."); form.management_reason.reportValidity(); return; } if (action === "DELETE" && button.dataset.confirm !== "yes") { button.dataset.confirm = "yes"; button.textContent = "Click again to permanently revoke"; return; } button.disabled = true; try { await mutate(`/admin/key-requests/${item.dataset.keyRequest}/management`, "PATCH", { action, reason_code: form.reason_code.value, reason: form.management_reason.value }); await keyRequests(); } catch (error) { button.disabled = false; form.management_reason.setCustomValidity(error.message); form.management_reason.reportValidity(); } }));
    document.querySelectorAll(".review-form").forEach((form) => form.addEventListener("submit", async (event) => { event.preventDefault(); const detail = form.closest("[data-review]"); const button = form.querySelector("button"); button.disabled = true; try { await mutate(`/admin/access-requests/${detail.dataset.review}`, "PATCH", { outcome: form.outcome.value, reason: form.reason.value }); detail.remove(); } catch (error) { button.disabled = false; form.reason.setCustomValidity(error.message); form.reason.reportValidity(); } }));
  }

  async function accounts() {
    const [accounts, credentials] = await Promise.all([get("/admin/accounts"), get("/admin/credentials")]);
    const rows = credentials.map((item) => { const limits = item.grant?.limits || {}; const revoked = item.status === "revoked"; return `<tr><td><code>${e(item.key_prefix)}…</code><small>${e(item.label || item.id)}</small></td><td>${badge(item.status)} <small>${badge(item.grant?.risk_state || item.risk_level)}</small></td><td><form class="key-editor" data-key="${e(item.id)}"><select name="status"${revoked ? " disabled" : ""}><option${item.status === "active" ? " selected" : ""}>active</option><option${item.status === "throttled" ? " selected" : ""}>throttled</option><option${item.status === "suspended" ? " selected" : ""}>suspended</option>${revoked ? `<option selected>revoked</option>` : ""}</select><input class="caps" name="capabilities" value="${e((item.grant?.capabilities || []).join(", "))}" aria-label="Capabilities"${revoked ? " disabled" : ""}><input type="number" min="1" name="rpm" value="${e(limits.rpm || 10)}" aria-label="RPM"${revoked ? " disabled" : ""}><input type="number" min="1" name="pending" value="${e(limits.pending || 10)}" aria-label="Pending limit"${revoked ? " disabled" : ""}><input type="number" min="1" name="approvals_month" value="${e(limits.approvals_month || 50)}" aria-label="Monthly approvals"${revoked ? " disabled" : ""}><input type="number" min="0" name="emails_month" value="${e(limits.emails_month || 30)}" aria-label="Monthly emails"${revoked ? " disabled" : ""}><select class="key-reason-code" name="action_reason_code" aria-label="Reason category"${revoked ? " disabled" : ""}><option value="ABUSE_SUSPECTED">Suspected abuse</option><option value="ABUSE_CONFIRMED">Confirmed abuse</option><option value="NO_LONGER_NEEDED">No longer needed</option><option value="ISSUED_BY_MISTAKE">Issued by mistake</option><option value="INTERNAL_TEST_CLEANUP">Internal test cleanup</option></select><input class="key-reason" name="action_reason" maxlength="500" placeholder="Reason for suspension or deletion"${revoked ? " disabled" : ""}><span class="key-actions"><button class="button" type="submit"${revoked ? " disabled" : ""}>Save</button><button class="button secondary rotate" type="button"${revoked ? " disabled" : ""}>Rotate</button><button class="button danger credential-delete" type="button"${revoked ? " disabled" : ""}>Delete key</button></span></form></td><td>${when(item.last_used_at)}</td></tr>`; });
    const accountRows = accounts.map((item) => `<tr><td>${e(item.email)}</td><td>${badge(item.email_verified_at ? "verified" : "unverified")}</td><td>${when(item.first_request_at)}</td><td>${when(item.first_production_action_at)}</td><td>${when(item.created_at)}</td></tr>`);
    root.innerHTML = head("Accounts and keys", "Pause safely. Delete permanently.", "Suspension can be restored after investigation. Delete immediately revokes the key and keeps its usage, cost, incident, and audit history.") + `<div class="notice" id="secret"></div>${panel("Credentials", "Limit columns: RPM, pending, approvals/month, emails/month. A deletion reason is required.", table(["Key", "State", "Limits and action", "Last used"], rows), credentials.length)}<div class="toolbar"><h2>Verified accounts</h2><span>Activation milestones</span></div>${panel("Accounts", "Email verification and first production success.", table(["Account", "Verification", "First request", "First production action", "Created"], accountRows), accounts.length)}`;
    document.querySelectorAll(".key-editor").forEach((form) => {
      form.addEventListener("submit", async (event) => { event.preventDefault(); const button = form.querySelector("button[type=submit]"); form.action_reason.setCustomValidity(""); if (form.status.value === "suspended" && !form.action_reason.value.trim()) { form.action_reason.setCustomValidity("Record why this key is being suspended."); form.action_reason.reportValidity(); return; } button.disabled = true; try { await mutate(`/admin/credentials/${form.dataset.key}`, "PATCH", { status: form.status.value, risk_level: form.status.value === "active" ? "low" : form.status.value === "throttled" ? "high" : "critical", capabilities: form.capabilities.value.split(",").map((value) => value.trim()).filter(Boolean), limits: { rpm: +form.rpm.value, pending: +form.pending.value, approvals_month: +form.approvals_month.value, emails_month: +form.emails_month.value }, revoke_reason_code: form.status.value === "suspended" ? form.action_reason_code.value : undefined, revoke_reason: form.status.value === "suspended" ? form.action_reason.value.trim() : undefined }); button.textContent = "Saved"; setTimeout(() => { button.textContent = "Save"; button.disabled = false; }, 900); } catch (error) { button.disabled = false; button.textContent = "Failed"; } });
      form.querySelector(".rotate").addEventListener("click", async (event) => { const button = event.currentTarget; if (button.dataset.confirm !== "yes") { button.dataset.confirm = "yes"; button.textContent = "Rotate now"; return; } button.disabled = true; try { const result = await mutate(`/admin/credentials/${form.dataset.key}/rotate`, "POST"); const secret = document.getElementById("secret"); secret.textContent = `Copy the new key now: ${result.key}`; secret.classList.add("show"); form.status.value = "revoked"; button.textContent = "Rotated"; } catch (error) { button.disabled = false; button.textContent = "Try again"; } });
      form.querySelector(".credential-delete").addEventListener("click", async (event) => { const button = event.currentTarget; form.action_reason.setCustomValidity(""); if (!form.action_reason.value.trim()) { form.action_reason.setCustomValidity("Record why this key is being deleted."); form.action_reason.reportValidity(); return; } if (button.dataset.confirm !== "yes") { button.dataset.confirm = "yes"; button.textContent = "Click again to revoke"; return; } button.disabled = true; try { await mutate(`/admin/credentials/${form.dataset.key}`, "PATCH", { status: "revoked", risk_level: "critical", revoke_reason_code: form.action_reason_code.value, revoke_reason: form.action_reason.value.trim() }); await accounts(); } catch (error) { button.disabled = false; form.action_reason.setCustomValidity(error.message); form.action_reason.reportValidity(); } });
    });
  }

  async function traffic() {
    const usage = await get("/admin/traffic"); const totals = usage.reduce((a, row) => ({ approvals: a.approvals + row.approvals_created, decisions: a.decisions + row.decisions, callbacks: a.callbacks + row.callback_attempts, failures: a.failures + row.callback_failures }), { approvals: 0, decisions: 0, callbacks: 0, failures: 0 });
    const rows = usage.map((item) => `<tr><td>${e(item.day)}</td><td><code>${e(item.credential_id)}</code></td><td>${num(item.approvals_created)}</td><td>${num(item.decisions)}</td><td>${num(item.callback_attempts)}</td><td>${num(item.callback_failures)}</td></tr>`);
    root.innerHTML = head("Traffic", "Watch volume before it becomes cost.", "Daily protected actions and callback work are attributed to credentials. Risk monitoring uses shorter rolling windows in the background.") + `<section class="metrics"><div class="metric"><span>Created</span><strong>${num(totals.approvals)}</strong></div><div class="metric"><span>Decisions</span><strong>${num(totals.decisions)}</strong></div><div class="metric"><span>Callback attempts</span><strong>${num(totals.callbacks)}</strong></div><div class="metric ${totals.failures ? "alert" : ""}"><span>Callback failures</span><strong>${num(totals.failures)}</strong></div></section>${panel("Daily usage", "Most recent records first.", table(["Day", "Credential", "Created", "Decisions", "Callback attempts", "Failures"], rows), usage.length)}`;
  }

  async function reliability() {
    const data = await get("/admin/reliability"); const callbackTotal = data.callbacks.reduce((sum, item) => sum + item.count, 0); const delivered = data.callbacks.find((item) => item.state === "delivered")?.count || 0; const rate = callbackTotal ? delivered / callbackTotal * 100 : 100;
    const bars = `<div class="bars">${data.callbacks.map((item) => `<div class="bar"><span>${e(item.state)}</span><div class="bar-track"><i style="width:${callbackTotal ? item.count / callbackTotal * 100 : 0}%"></i></div><b>${num(item.count)}</b></div>`).join("")}</div>`;
    const rows = data.recent_deliveries.map((item) => `<tr><td>${when(item.at)}</td><td><code>${e(item.approval_id)}</code></td><td>${num(item.attempt)}</td><td>${item.status_code ? num(item.status_code) : "—"}</td><td>${e(item.error || "—")}</td></tr>`);
    root.innerHTML = head("Reliability", "A decision is only useful when it arrives.", "Callback retries preserve the same approval ID. Gone one-time endpoints stop retrying; transient failures remain queued until the retry budget ends.") + `<section class="metrics"><div class="metric"><span>Delivery rate</span><strong>${rate.toFixed(1)}%</strong></div><div class="metric"><span>Delivered</span><strong>${num(delivered)}</strong></div><div class="metric"><span>Total outbox</span><strong>${num(callbackTotal)}</strong></div></section><div class="split">${panel("Callback states", "Current outbox distribution.", bars)}${panel("Delivery attempts", "Latest provider responses.", table(["Time", "Approval", "Attempt", "HTTP", "Error"], rows), rows.length)}</div>`;
  }

  async function incidents() {
    const data = await get("/admin/incidents"); const open = data.incidents.filter((item) => item.status === "OPEN").length; const rows = data.incidents.map((item) => `<tr><td>${when(item.created_at)}</td><td>${badge(item.severity)}</td><td><b>${e(item.title)}</b><small>${e(item.credential_id || "global")}</small></td><td>${badge(item.status)}</td><td><div class="actions">${item.status === "OPEN" ? `<button class="button secondary incident-action" data-id="${e(item.id)}" data-status="ACKNOWLEDGED">Acknowledge</button>` : ""}${item.status !== "RESOLVED" ? `<button class="button incident-action" data-id="${e(item.id)}" data-status="RESOLVED">Resolve</button>` : ""}</div></td></tr>`);
    const signalRows = data.signals.map((item) => `<tr><td>${when(item.at)}</td><td>${e(item.signal_type)}</td><td>${badge(item.severity)}</td><td><code>${e(item.credential_id || "global")}</code></td><td>${num(item.observed_value)} / ${item.baseline_value == null ? "—" : num(item.baseline_value)}</td></tr>`);
    root.innerHTML = head("Incidents", "Contain first. Investigate from one record.", "Only high and critical incidents wake the operator in Slack. This screen keeps the complete state and evidence history.") + `<section class="metrics"><div class="metric ${open ? "alert" : ""}"><span>Open</span><strong>${num(open)}</strong></div><div class="metric"><span>All incidents</span><strong>${num(data.incidents.length)}</strong></div><div class="metric"><span>Recent signals</span><strong>${num(data.signals.length)}</strong></div></section>${panel("Incident queue", "Acknowledge ownership, then resolve after investigation.", table(["Created", "Severity", "Incident", "State", "Action"], rows), data.incidents.length)}<div class="toolbar"><h2>Signal evidence</h2><span>Rolling baseline and rules</span></div>${panel("Recent risk signals", "No request body or raw IP is stored here.", table(["Observed", "Signal", "Severity", "Credential", "Value / baseline"], signalRows), data.signals.length)}`;
    document.querySelectorAll(".incident-action").forEach((button) => button.addEventListener("click", async () => { button.disabled = true; try { await mutate(`/admin/incidents/${button.dataset.id}`, "PATCH", { status: button.dataset.status }); await incidents(); } catch (error) { button.disabled = false; button.textContent = "Failed"; } }));
  }

  async function costs() {
    const data = await get("/admin/costs"); const max = Math.max(0.000001, ...data.by_category.map((item) => item.estimated));
    const bars = `<div class="bars">${data.by_category.map((item) => `<div class="bar"><span>${e(item.category)}</span><div class="bar-track"><i style="width:${item.estimated / max * 100}%"></i></div><b>${money(item.estimated)}</b></div>`).join("")}</div>`;
    const keyRows = data.top_keys.map((item) => `<tr><td><code>${e(item.credential_id || "unattributed")}</code></td><td>${money(item.estimated)}</td></tr>`);
    root.innerHTML = head("Costs", "Estimate now. Reconcile later.", "The live ledger gives an early warning. Provider invoices remain separate actual costs, so estimates never pretend to be settled bills.") + `<section class="metrics"><div class="metric"><span>Estimated today</span><strong>${money(data.today.estimated)}</strong></div><div class="metric"><span>Estimated MTD</span><strong>${money(data.mtd.estimated)}</strong></div><div class="metric"><span>Actual MTD</span><strong>${money(data.mtd.actual)}</strong></div><div class="metric"><span>Projected month</span><strong>${money(data.projected_month_estimated_usd)}</strong></div></section><div class="split">${panel("Cost categories", "Compute, storage, delivery, retries, and providers.", bars || empty("No cost entries", "Costs appear after protected actions."))}${panel("Unit cost", "Current month estimates.", `<div class="stack"><div class="event"><i></i><div><b>Protected action</b><small>request, storage, and delivery</small></div><time>${money(data.unit_costs.per_protected_action)}</time></div><div class="event"><i></i><div><b>Email</b><small>transactional delivery</small></div><time>${money(data.unit_costs.per_email)}</time></div><div class="event"><i></i><div><b>Callback attempt</b><small>external delivery</small></div><time>${money(data.unit_costs.per_callback)}</time></div></div>`)}</div><div class="toolbar"><h2>Largest cost keys</h2><span>Global guardrail ${money(data.guardrails.global_daily_usd)} / day</span></div>${panel("Top credentials", "Estimated month-to-date attribution.", table(["Credential", "Estimated cost"], keyRows), keyRows.length)}`;
  }

  const screens = { "/admin": overview, "/admin/key-requests": keyRequests, "/admin/accounts": accounts, "/admin/traffic": traffic, "/admin/reliability": reliability, "/admin/incidents": incidents, "/admin/costs": costs };
  Promise.resolve(screens[page] ? screens[page]() : overview()).catch(showError);
})();
