// 추가 기능 점검: 관리자 키 발급 → 승인 생성, 수동 요청, 데모, 랜딩
const { spawn } = require("child_process");
const fs = require("fs");
const path = require("path");
const http = require("http");
const tmp = fs.mkdtempSync("/tmp/someonehastosayyes-test2-");
const dbPath = path.join(tmp, "test.db");
const mail = http.createServer((req,res)=>{req.resume();req.on("end",()=>{res.writeHead(200,{"content-type":"application/json"});res.end('{"id":"email_test"}')})}).listen(3993,"127.0.0.1");
const srv = spawn("node", ["server.js"], { env: { ...process.env, PORT: 3997, BASE_URL: "http://localhost:3997", API_KEYS: "k1", DB_PATH: dbPath, SIGNING_SECRET: "s", ADMIN_SECRET: "adm", ALLOW_DIRECT_ADMIN_KEYS: "true", RESEND_API_KEY: "re_test", RESEND_API_URL: "http://127.0.0.1:3993/emails", EMAIL_FROM: "test@example.com" }, stdio: "inherit" });
const sleep = (ms) => new Promise(r=>setTimeout(r,ms));
(async () => {
  await sleep(700);
  const B = "http://localhost:3997";
  let r = await fetch(B + "/"); const html = await r.text(); console.log("landing", r.status, html.includes("Human approval for any automation"), html.includes("/v1/approvals"));
  r = await fetch(B + "/admin/keys", { method:"POST", headers:{ "content-type":"application/json", "x-admin-secret":"adm" }, body: JSON.stringify({ label:"steve@n8n-thread" }) });
  const k = await r.json(); console.log("admin key", r.status, k.key.startsWith("ah_"), k.slack_install_url.includes("?token="), !k.slack_install_url.includes(k.key));
  r = await fetch(B + "/v1/approvals", { method:"POST", headers:{ "content-type":"application/json", authorization:"Bearer "+k.key }, body: JSON.stringify({ question:"with db key" }) });
  console.log("db key works", r.status);
  r = await fetch(B + "/v1/approvals", { method:"POST", headers:{ "content-type":"application/json", authorization:"Bearer demo" }, body: JSON.stringify({ question:"x", channel:"slack", to:"C1" }) });
  console.log("public demo credential blocked", r.status);
  r = await fetch(B + "/demo", { method:"POST", headers:{ "content-type":"application/json" }, body: JSON.stringify({ question:"demo q" }) });
  const d = await r.json(); console.log("demo create", r.status, !!d.approve_url);
  await fetch(d.approve_url, { method:"POST", headers:{ "content-type":"application/x-www-form-urlencoded" }, body:"decision=approved&name=visitor" });
  const s = await (await fetch(d.status_url)).json(); console.log("demo status", s.status, s.decided_by, s.callback);
  r = await fetch(B + "/request-key", { method:"POST", headers:{ "content-type":"application/json" }, body:JSON.stringify({ email:"a@b.co", tool:"n8n", delivery:"link" }) });
  const request = await r.json(); console.log("manual request queued", r.status, request.status, !!request.request_id);
  const queued = await (await fetch(B + "/admin/key-requests", { headers:{ "x-admin-secret":"adm" } })).json();
  console.log("request visible to admin", queued[0]?.email, queued[0]?.tool, queued[0]?.delivery, queued[0]?.status);
  r = await fetch(B + "/create-key", { method:"POST", headers:{ "content-type":"application/json" }, body:JSON.stringify({ email:"b@b.co", tool:"n8n", delivery:"link" }) });
  console.log("public auto-issuance blocked", r.status);
  r = await fetch(B + "/slack/install?key=" + k.key); console.log("slack install without client id →", r.status);
  srv.kill(); mail.close(); fs.rmSync(tmp, { recursive:true, force:true }); process.exit(0);
})().catch(e=>{ console.error(e); srv.kill(); mail.close(); fs.rmSync(tmp, { recursive:true, force:true }); process.exit(1); });
